export const FETCH_MOVIES="FETCH_MOVIES";
export const FETCH_SUCCEDED="FETCH_SUCCEDED";
export const FETCH_FAILED="FETCH_FAILED";
export const ARRAY_EMPTY="ARRAY_EMPTY";
export const FETCH_MOVIE_DETAIL="FETCH_MOVIES_DETAIL";
export const FETCH_SUCCEDED_DETAIL="FETCH_SUCCEDED_DETAIL";
export const FETCH_FAILED_DETAIL="FETCH_FAILED_DETAIL";